### ISSUE TITLE
Delete result page error

### ISSUE THREAD

**Issue by takesson** [Reposoft/rweb#21]
`Runtime error (code 8): Only variables should be passed by reference `

Reproduced on 1.6.2 and 1.6.3.

**Comment by solsson** [comment]
I forgot to backport https://github.com/Reposoft/rweb/commit/f7b2956d41a8b5d54bf66a198f7aa39c97090069. Will do that together with the fix for #22.

**Comment by solsson** [comment]
In 1.6.x since 5a7cc8a9. I think it's an ugly gotcha for a programming language to have.

**Comment by takesson** [comment]
Insane gotcha. Gotta love PHP.

**Comment by solsson** [comment]
Released v1.6.5 in 4c361a4c.

**Comment by takesson** [comment]
Confirmed fixed in v1.6.5.
