### ISSUE TITLE
Browsers do not respect the OS date format settings

### ISSUE THREAD

**Issue by takesson** [Reposoft/rweb#27]
Increasing amounts of users want to use a browser running in English locale but see date formats appropriate for their region. So far, only requested by users who expect an ISO formatted date.

Date format in "history" and other pages are managed Browser-side by:
https://github.com/Reposoft/rweb/tree/master/repos-plugins/dateformat

It uses `Date.toLocaleString()` which is highly browser dependent:
 - IE does the right thing (!). It uses the OS date format settings regardless of locale / accept-languages.
 - Chrome strictly uses the language of its UI and assumes language and date formats should always be connected. It does not matter how accept-languages are configured, only the UI language matters. 
 - FF used to separate the accept-language and the UI language to ensure configurability. I think it used the highest ranked accept-language (needs confirmation).
 - FF 57+ is now as stupid as Chrome. REGRESSION.

**Comment by takesson** [comment]
Suggested solution:
Both Chrome and FF allows the accept-languages list to contain both languages (e.g. "en") and locales (e.g. "en-US"). The list is available in Javascript with `navigator.languages`.

 - When a user has only a language as the top value, say "en", it can be interpreted as: "I want pages in English and I have no preference regarding number/date formats." When a user has no preference, the sane default is an ISO format with 24h clock.
 - When a user has a full locale as the top value, the user has indicates a preference regarding formats as well as language. Rweb can keep the current behaviour, which more or less assumes that the Browser is running in the same locale as the top value in accept-languages. I.e. the user can easily keep the current behaviour by setting "en-US" at the top instead of "en".

TODO: Also need to consider timezone.

**Comment by solsson** [comment]
I've tested 10c39b4 locally but all my browsers already had OS locale == navigator.languages.

> TODO: Also need to consider timezone.

Haven't looked into that.

**Comment by takesson** [comment]
Will test tomorrow. Timezone is likely not an issue unless using the options parameter of toLocaleString().

**Comment by takesson** [comment]
I installed Firefox ESR which is currently version 52.5.2 on Windows in order to figure out what it used to do. It respects the Windows-Region-Format setting, only the primary region (not if you also configure specific formats below).

It seems like Firefox 57 does not respect this setting (works like Chrome), confirmed on macOS but would require another test on Windows.

**Comment by takesson** [comment]
Can confirm that the above commit:
 - Makes Chrome respect the top accept-language.
 - Makes FF 57 respect the top accept-language.
 - Both Chrome and FF still displays in local timezone, good.
 - IE still respects the Windows Region settings, likely because it does not implement `navigator.languages`.

https://github.com/Reposoft/rweb/commit/10c39b48ce015631c11f7ea61a361b3ee7875dba

**Comment by takesson** [comment]
I would consider that commit safe (unless it needs more guarding for browsers that don't support parameters to toLocaleString) and a major step forward. 

It does not allow a user to get English text but ISO formats. I will email the most vocal customer to clarify their IT policy.

**Comment by takesson** [comment]
I have tested the approach of doing ISO format if the top accept-language is just a language, not a locale. 
```
                var display;
                if (toLocales != undefined && toLocales[0] && toLocales[0].length == 2) {
                        display = date.toLocaleString('sv'); // Use ISO format if the top accept-language does not explicitly request a region/format. Using 'sv' but could be any language using ISO format.
                } else {
                        display = date.toLocaleString(toLocales);
                }
```

**Comment by solsson** [comment]
https://github.com/Reposoft/rweb/commit/5aaa6ea60ac2fc10393d25628d3cac79dbe7329e adds the above. Released as https://github.com/Reposoft/rweb/releases/tag/v1.7.4 @takesson.

**Comment by takesson** [comment]
Verified in 1.7.4 with Chrome on Mac.
