### ISSUE TITLE
Dependency pdftk not available in Ubuntu 18.04

### ISSUE THREAD

**Issue by takesson** [Reposoft/rweb#29]
Rweb uses pdftk to extract PDF pages. I don't think Graphicsmagick uses pdftk (it uses gs).

Etymology:
 - pdftk is a frontend to iText (Java).
 - pdftk and/or iText depends on GCJ (compiles Java to native?)
 - Ubuntu 18.04 drops GCJ (?)
 - iText changed licenses and was forked into OpenPDF which seems reasonably maintained. https://github.com/LibrePDF/OpenPDF/releases

References:
https://askubuntu.com/questions/1029450/how-to-install-pdftk-on-ubuntu-18-04-bionic
bugs.launchpad.net/ubuntu/+source/pdftk/+bug/1764450

**Comment by takesson** [comment]
Alternative 1: Install older packages. I don't like that.

Alternative 2: Use a Java fork and make a command. Ok by me since we have a JRE anyway,
https://askubuntu.com/questions/1028522/how-can-i-install-pdftk-in-ubuntu-18-04-bionic-shell-version-no-gtk
https://coderwall.com/p/ssuaxa/how-to-make-a-jar-file-linux-executable

Alternative 3: Investigate if pdfseparate could be used instead.
http://www.linux-commands-examples.com/pdfseparate

**Comment by takesson** [comment]
The poppler project that provides pdfseparate seems reasonably alive.
https://anonscm.debian.org/cgit/pkg-freedesktop/poppler.git

**Comment by solsson** [comment]
I've tried [pdfseparate](https://manpages.debian.org/stretch/poppler-utils/pdfseparate.1.en.html) from https://packages.debian.org/stretch/poppler-utils on Stretch, but failed to use stdin as source pdf. It's really a must for large PDFs. Giving up for today.

```
diff --git a/repos-plugins/thumbnails/convert/graphicstransforms.inc.php b/repos-plugins/thumbnails/convert/graphicstransforms.inc.php
index 36ea3b2..7304eea 100644
--- a/repos-plugins/thumbnails/convert/graphicstransforms.inc.php
+++ b/repos-plugins/thumbnails/convert/graphicstransforms.inc.php
@@ -143,7 +143,7 @@ class ReposGraphicsTransformExtract extends ReposGraphicsTransformBase {
 		}
 		$page = $_REQUEST['page'];
 		unset($_REQUEST['page']); // disable default page handling
-		return 'pdftk - cat '.$page.' output "'.$tempfile.'"';
+		return 'pdfseparate -l '.$page.' - "'.$tempfile.'"';
 	}
 
 }
```

**Comment by takesson** [comment]
That is an epic omission...

**Comment by takesson** [comment]
This indicates that it should work:
https://lists.freedesktop.org/archives/poppler/2011-May/007480.html

I get the impression that both -l and -f should be specified.

**Comment by solsson** [comment]
I'll take another look.

**Comment by solsson** [comment]
The mailing list reply is clear enough but I failed again

```
$> svn cat http://svn/svn/test1/test.pdf | pdfseparate -f 2 -l 2 - tmp2.pdf
I/O Error: Couldn't open file '-': No such file or directory.
Syntax Error: Could not extract page(s) from damaged file ('-')
$> svn cat http://svn/svn/test1/test.pdf > tmp.pdf
$> pdfseparate -f 2 -l 2 tmp.pdf tmp2.pdf
# worked
```

Without the dash I get a help text. `pdfseparate version 0.48.0`...

Next step is probably to look for more alternatives, but kids' daycare won't wait for that :)

**Comment by solsson** [comment]
@takesson Please try https://github.com/Reposoft/rweb/releases/tag/v1.7.8

**Comment by takesson** [comment]
I have done some research and found that CMS does not use the extract feature of Rweb. That explains why we have no testbeat coverage of PDF extract.

Sorry, I have no tests or code that exercises the extract.

Thanks for the release. I can now safely remove pdftk.

**Comment by takesson** [comment]
Had a quick look at pdfseparate. Also unable to make stdin work.

However, pdfinfo works with both `-`and `fd://0`.
