### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by takesson** [Reposoft/rweb#37]
```
[14-May-2022 19:42:52 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /srv/cms/rweb/repos-web/conf/repos.properties.php:109
Stack trace:
#0 /srv/cms/rweb/repos-web/index.php(6): require()
#1 {main}
  thrown in /srv/cms/rweb/repos-web/conf/repos.properties.php on line 109
```

**Comment by takesson** [comment]
More PHP 8:
```
[16-May-2022 09:53:57 UTC] PHP Fatal error:  Uncaught Error: Non-static method Presentation::getInstance() cannot be called statically in /srv/cms/rweb/repos-web/index.php:9
Stack trace:
#0 {main}
  thrown in /srv/cms/rweb/repos-web/index.php on line 9
```

**Comment by takesson** [comment]
Looks like Repos' System class needs to ensure some functions are declared static.

**Comment by solsson** [comment]
It seems they have removed 20 years' worth of deprecated APIs 🙂

Please try https://github.com/Reposoft/rweb/releases/tag/v1.8.0. I don't expect anything but happy paths to work, but because I had to update build & test workflows we should make sure the release is actually installable before I continue. Also script builds are non-reproducible due to how npm works so please try things like thumbnailing and syntax highlighting.

Changes:
- https://github.com/Reposoft/rweb/compare/php8?expand=1
- https://github.com/Reposoft/docker-svn/pull/16

**Comment by takesson** [comment]
```
<h1>An error occurred</h1>
<p><em>Runtime error (code 8): tempnam(): file created in the system's temporary directory


<!-- Error level 8. Stack trace:
file	line	function
/srv/cms/rweb/repos-web/conf/System.class.php	489	tempnam
/srv/cms/rweb/repos-web/conf/System.class.php	169	_getSystemTemp
/srv/cms/rweb/repos-web/lib/smarty/smarty.inc.php	49	getApplicationTemp
/srv/cms/rweb/repos-web/conf/Presentation.class.php	191	smarty_getInstance
/srv/cms/rweb/repos-web/conf/Presentation.class.php	155	__construct
/srv/cms/rweb/repos-web/index.php	9	getInstance
 -->

</em></p>
```

**Comment by takesson** [comment]
Trying explicitly setting TMP in FPM pool config:
```
env[TMP] = /tmp
```

Also noted that version reported in html footer is still 1.7.

**Comment by takesson** [comment]
Syntax highlighting works.

Thumbnailing is broken:
```
Runtime error (type 2): Undefined property: ReposGraphicsTransformThumb::$source

file	line	function
/srv/cms/rweb/repos-plugins/thumbnails/convert/graphicstransforms.inc.php	71	reportError
/srv/cms/rweb/repos-plugins/thumbnails/convert/index.php	110	getOutputFormat

```

**Comment by solsson** [comment]
Looks like nothing fundamental is broken with how I got started. I can proceed from here though I might not find a repro for the `tempnam` issue in my docker based stack.

**Comment by takesson** [comment]
Try unsetting all (3?) env vars used for temp. Otherwise the fallback route using tempnam should be removed and throw explicit error. 

Do you have more than thumbnailing on the backlog?

**Comment by solsson** [comment]
I think edit operations need more testing, in particular file upload, with weird input values that need escaping.

**Comment by solsson** [comment]
I created followup issues and released https://github.com/Reposoft/rweb/releases/tag/v1.8.1 from main after testing basic flows again.

**Comment by takesson** [comment]
Was thumbnailing fixed before merge?

**Comment by solsson** [comment]
Sorry I should have documented here.

[This commit](https://github.com/Reposoft/rweb/commit/f13b1d87cd4c158652b85e02f27cbe6eb6090446) fixed thumbnailing. The PHP 8 change in constructor naming might have caused more yet unknown regressions. Sadly functions named like the class are still valid but just not invoked anymore. This means that the code might run but without fields being initialized. It's really hard to know if I've found all instances of legacy constructors.

The other major challenge was the change from curly braces to brackets for accessing characters in strings. There's some low level code doing for example [json encoding](https://github.com/Reposoft/rweb/commit/c0c99e19adf0ec75cd31f078e37e3df4f5de4371#diff-b358f7e15228d03e1f40affd6a88d0ebfb28124034cfb99b68184e339c7ff615) and tar decompression that had lots of string maniupulation affected by the change. There's probably libraries for such things nowadays, so if you notice instability it could be worthwhile to throw out old code.

**Comment by takesson** [comment]
Test suite passed. Thanks.

Not sure how to roll this out since we have recently made a release. Might bundle with updated authentication.

**Comment by solsson** [comment]
There are no other improvements from 1.7.x than PHP 8 compatibility, so you can wait until you're upgrading PHP.
