### ISSUE TITLE
Result pages display the backend host

### ISSUE THREAD

**Issue by takesson** [Reposoft/rweb#42]
Not sure if this applies to all result pages.

Example:

New version committed
http://simonsoft.simonsoftcms.se:8090/svn/documentation/access.accs is at revision 4500

**Comment by solsson** [comment]
I can't confirm this with the docker-compose based stack. The apache host has a random hostname, I don't see `ServerName` enabled anywhere, and it reports the external http host at that location.

I'm surprised the setup is operational when reporting an internal URL there. Many links should fail. The result page uses [getTargetUrl()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/edit/upload/index.php#L231) which [reuses](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/edit/upload/index.php#L363) the global [getTargetUrl()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/account/login.inc.php#L292) which is documented as [returns the absolute URL as the user knows it.](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/account/login.inc.php#L17). This is truly ancient code 😄 .

 If I remember correctly you have some control over those URLs through [getRepositoryRoot()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/conf/repos.properties.php#L185)'s and [getHost()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/conf/repos.properties.php#L374)'s use of server vars, which I think propagate from [SetEnv](https://httpd.apache.org/docs/2.4/mod/mod_env.html#setenv).

**Comment by takesson** [comment]
> Not sure if this applies to all result pages.

Can see this on result pages for:
 - Edit in repos
 - add file
 - lock / unlock

**Comment by takesson** [comment]
> I can't confirm this with the docker-compose based stack. The apache host has a random hostname, I don't see `ServerName` enabled anywhere, and it reports the external http host at that location.

Is the svn backend url different from the external url? (apart from http/https)

> I'm surprised the setup is operational when reporting an internal URL there. Many links should fail. 

Any specific example that I can verify?

> The result page uses [getTargetUrl()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/edit/upload/index.php#L231) which [reuses](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/edit/upload/index.php#L363) the global [getTargetUrl()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/account/login.inc.php#L292) which is documented as [returns the absolute URL as the user knows it.](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/account/login.inc.php#L17). This is truly ancient code 😄 .

I think that documentation is optimistic 😄 .

It is not really necessary to display the full URL in the result pages. The user can just return to the details page to get the url. There is an issue with the encoding of file name appended to url as well (add file).

> If I remember correctly you have some control over those URLs through [getRepositoryRoot()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/conf/repos.properties.php#L185)'s and [getHost()](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/conf/repos.properties.php#L374)'s use of server vars, which I think propagate from [SetEnv](https://httpd.apache.org/docs/2.4/mod/mod_env.html#setenv).

Yes, I have this config:
```
SetEnv REPOS_HOST "http://simonsoft.simonsoftcms.se:8090"
```
The reason is that "http://simonsoft.simonsoftcms.se" is running OpenIDC and the https can be done by a different host or a load balancer.

**Comment by takesson** [comment]
> I'm surprised the setup is operational when reporting an internal URL there. Many links should fail.

Perhaps ProxyPassReverse does its job on href attributes.

**Comment by solsson** [comment]
How does `svn copy` work on this host? I ask because looking at how `getTargetUrl()` is used I suspect that the only difference between internal and external URLs that we support is TLS termination http<->https. Presentation uses `asLink` to display user-facing URLs. The tests for asLink are [here](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/conf/repos.properties.test.php#L200). Maybe this limited scope is on par with svn's scope for when copy works.

**Comment by solsson** [comment]
Would links work if the port number is dropped? If so we could possibly wrap [the URL](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/edit/upload/index.php#L231) with `asLink` and scope creep asLink to support dropping port numbers, by opt in using SetEnv for example.

**Comment by takesson** [comment]
> How does `svn copy` work on this host? 

 - rweb copy works
 - svn client copy works BUT that request is not proxied to the backend host, it is handles by the http host which does OpenIDC auth (the svn client presents a session Cookie). 

> I ask because looking at how `getTargetUrl()` is used I suspect that the only difference between internal and external URLs that we support is TLS termination http<->https. Presentation uses `asLink` to display user-facing URLs. The tests for asLink are [here](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/conf/repos.properties.test.php#L200). Maybe this limited scope is on par with svn's scope for when copy works.

When the backend host is actually a different host ( e.g. actual backend cluster) the svn client copy will also have to be proxied. I expect to make that work by enhancing this Apache config a bit (the statement needs to be specific to the hostname and backend url):
```
RequestHeader edit Destination ^https http early
```

**Comment by takesson** [comment]
> Would links work if the port number is dropped? If so we could possibly wrap [the URL](https://github.com/Reposoft/rweb/blob/v1.8.1/repos-web/edit/upload/index.php#L231) with `asLink` and scope creep asLink to support dropping port numbers, by opt in using SetEnv for example.

To clarify terminology:
 - "links", aka href attributes work fine, handled by ProxyPassReverse
 - "textual urls" display the backend url, classic issue in proxy situations

So let's consider what is the value of "textual urls"?
 - Details / Edit page footer: huge value, works fine (not sure why)
 - Result pages (only some result pages): no value or even negative value making the page more cluttered
 - ...?

I suggest removing "textual urls" except Details / Edit page footer in order to stay within the classic limitations of proxy setups and also benefiting from its flexibility.

Just removing the port number would work now but not when using an actual backend cluster. I don't understand why this isn't an issue in most dockerized setups.

**Comment by takesson** [comment]
I have realised that ProxyPassReverse is not handling the links because the PHP handler executes in the normal http vhost and there is never any proxying to the backend svn host at this time (no future intention either).

Is the PHP code actually using getTargetUrl() for generating hrefs in pages? Using relative links would be less problematic.

**Comment by solsson** [comment]
> Is the PHP code actually using getTargetUrl() for generating hrefs in pages?

Links should be relative. I think this issue is right to classify external-facing use of `getTargetUrl()` as a bug.

**Comment by solsson** [comment]
https://github.com/Reposoft/rweb/releases/tag/v1.8.4

**Comment by takesson** [comment]
Some clarification of earlier discussion:
- The ProxyPassReverse never processes href in the content. It only handles a few response headers, most importantly Location. It does not process the dav header Destination. 
- The Destination header might no longer matter with modern svn clients (using Serf probably). Unable to reproduce the copy issue even if adding additional proxy of the svn traffic (not via rweb).

**Comment by takesson** [comment]
Good progress but the lock / unlock result pages still display the backend url.

The Add File result page is much nicer now.

**Comment by solsson** [comment]
I need more time in order to set up an equivalent test environment.

Could it be that the result message `'<url>' locked by user '<user>'` comes from svn? I can't find such a string anywhere.

> The ProxyPassReverse never processes href in the content

This means that the `return to repository` URL must be fixed. That should be doable.

**Comment by takesson** [comment]
> I need more time in order to set up an equivalent test environment.

No need for now.

> Could it be that the result message `'<url>' locked by user '<user>'` comes from svn? I can't find such a string anywhere.

Yes, good catch. I can check if there are other Apache directives to fix that. 

> > The ProxyPassReverse never processes href in the content
> 
> This means that the `return to repository` URL must be fixed. That should be doable.

It works fine. Not sure why.

**Comment by takesson** [comment]
Do you have an account in an Azure AD tenant? Send me the Tenant UUID via email.

**Comment by takesson** [comment]
```
# Substitute internal svn url in result pages (lock, unlock, ...?).
<Location "/repos-web/view/">
        AddOutputFilterByType SUBSTITUTE text/html
        Substitute "s|http://<%= node['cms']['hostname'] %>:8090|https://<%= node['cms']['hostname'] %>|"
</Location>
```

**Comment by solsson** [comment]
That's really useful! Maybe you should use the [n](https://httpd.apache.org/docs/2.4/mod/mod_substitute.html#substitute) flag? Probably more performant, and the risk of false positives or invalid pattern is even lower.
